"use server";
// Functions to interact with file system
import { readdirSync, readFileSync } from 'fs';
// Extract metadata from Markdown files
import matter from "gray-matter";
// Handles file paths and directories
import path from "path";
// Parse and format dates
import moment from "moment";
// Parse and process Markdown content
import { remark } from "remark";
// Convert Markdown content to HTML
import html from "remark-html";

import type { ArticleItem } from "../types" 

// Store abs path of articles directory 
const articlesDirectory = path.join(process.cwd(), "articles")

// Get articles sorted by date
const getSortedArticles = (): ArticleItem[] => {
    // Read contents of articleDirectory; retrieves array of all Markdown files
    const fileNames = readdirSync(articlesDirectory)

    // Loop through each file:
    const allArticlesData = fileNames.map(fileName => {
        // ID generated by removing ".md" from filename
        const id = fileName.replace(/\.md$/, "")

        // Combine articles directory path with curr file name to get full path name
        const fullPath = path.join(articlesDirectory, fileName)
        // Content at full path read synchronously
        const fileContents = readFileSync(fullPath, "utf-8")

        // Process metadata of each article using matter
        const matterResult = matter(fileContents)

        return {
            id, 
            title: matterResult.data.title,
            date: matterResult.data.date,
            category: matterResult.data.category
        }
    })

    return allArticlesData.sort((a, b) => {
        const format = "DD-MM-YYYY"
        const dateOne = moment(a.date, format)
        const dateTwo = moment(b.date, format)
        if (dateOne.isBefore(dateTwo)) {
            // First object precedes 2nd
            return -1
        } else if (dateTwo.isBefore(dateOne)) {
            // 2nd object precedes 1st
            return 1
        } else {
            return 0
        }
    })
}

// Loop through articles and put into buckets based on categories
export const getCategorizedArticles = (): Record<string, ArticleItem[]> => {
    const sortedArticles = getSortedArticles()
    const categorizedArticles: Record<string, ArticleItem[]> = {}

    sortedArticles.forEach((article) => {
        // Make category bucket if it doesn't already exist
        if(!categorizedArticles[article.category]) {
            categorizedArticles[article.category] = []
        }
        categorizedArticles[article.category].push(article)
    })

    // Each key represents unique category and contains articles belonging to it
    return categorizedArticles
}
